// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvfkazkgugonkrktiurw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2ZmthemtndWdvbmtya3RpdXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDkyMjYsImV4cCI6MjA2MDcyNTIyNn0.fvW8jO8W_wmHG54WsVGq9eC-mPpbSZieyynJdsNDNJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);